name: szemeredi_game
description: "A Szemeredi Game for combinatorial games project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.2
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ffigen
  ffigen: ^11.0.0

  # linters
  flutter_lints: ^2.0.0
  leancode_lint: ^11.0.0

flutter:
  uses-material-design: true

ffigen:
  name: 'SzemerediGameEngine'
  description: 'Bindings to SzemerediGameEngine'
  output: 'lib/utils/ffi_bindings.dart'
  headers:
    entry-points:
    - 'game_engine/api.h'
#    include-directives:
#    - 'game_engine/api.h'
