name: szemeredi_game
description: "A Szemeredi Game for combinatorial games project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linters
  flutter_lints: ^2.0.0
  leancode_lint: ^11.0.0

flutter:
  uses-material-design: true
